AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 200

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Layout/LineLength:
  Max: 180
